---
name: "Lint"
on: # yamllint disable-line rule:truthy rule:comments
  push:
    branches:
      - "main"
  pull_request: ~
permissions: "read-all"

jobs:
  build:
    name: Lint Everything
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_HTML_PRETTIER: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
